config/routes.rb
Popdisco::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get 'posts/popular' => 'posts#popular_posts', :as => :popular_posts

  resources :posts do
    resources :comments
  end

  get 'organizations/recent' => 'organizations#recent_organizations', :as => :recent_organizations
  get 'organizations/reputation' => 'organizations#top_organizations', :as => :top_organizations
  get 'organizations/:id/join' => 'organizations#join', :as => :join_organization

  resources :organizations, :except => :destroy

  get "omniauth_callbacks/facebook"

  devise_for :users, :controllers => { :omniauth_callbacks => 'omniauth_callbacks' }

  resources :user_profiles, except: [:index, :show, :destroy]

  get 'members' => 'members#index'
  get 'members/recent' => 'members#recent_members', :as => :recent_members
  get 'members/reputation' => 'members#members_by_reputation', :as => :top_members
  get 'members/:id' => 'members#show', :as => :member

  get 'posts/:id/counterpoints/new' => 'posts#new_counterpoint', :as => :new_post_counterpoint
  post 'posts/:id/counterpoints' => 'posts#create_counterpoint', :as => :post_counterpoints

  get 'topics/:tag/posts' => 'tags#posts_by_tag', :as => :posts_by_tag
  get 'topics' => 'tags#index'
  get 'topics/recent' => 'tags#recent_tags', :as => :recent_topics
  get 'topics/popular' => 'tags#popular_tags', :as => :popular_topics

  match 'vote/post/:post_id/up' => 'votes#vote_post_up', :as => :vote_post_up
  match 'vote/post/:post_id/down' => 'votes#vote_post_down', :as => :vote_post_down
  match 'vote/comment/:comment_id/up' => 'votes#vote_comment_up', :as => :vote_comment_up
  match 'vote/comment/:comment_id/down' => 'votes#vote_comment_down', :as => :vote_comment_down

  get "achievements" => 'achievements#index', :as => :achievements
  get "achievements/:id" => 'achievements#show', :as => :achievement

  get "achievements/show"

  root :to => 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user, :counter_cache => true
  has_and_belongs_to_many :counter_points, :class_name => 'Post', :join_table => 'counter_points', :association_foreign_key => 'counter_point_id', :foreign_key => 'post_id'
  has_many :comments
  has_many :post_votes
  acts_as_taggable

  validates_presence_of :title, :body, :user

  def up_vote_count
    PostVote.count(:conditions => "post_id = #{id} and vote = 1")
  end

  def down_vote_count
    PostVote.count(:conditions => "post_id = #{id} and vote = -1")
  end

  def user_can_edit?(user)
    !user.nil? and user.id == user_id
  end

  def user_can_post_counterpoint?(user)
    !user.nil? and user.id != user_id
  end

  def user_can_vote?(voter)
    #author cannot vote on their own post
    if voter.nil? or (voter.id == user_id)
      return false
    end

    #voter cannot vote more than once
    post_votes.each do |vote|
      if vote.user_id == voter.id
        return false
      end
    end

    true
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index, :popular_posts]

  before_filter :requires_author, only: [:edit, :update]

  before_filter :requires_new_author, only: [:new_counterpoint, :create_counterpoint]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order('created_at desc, vote_count_cache desc').page params[:page]

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  def popular_posts
    @posts = Post.order('vote_count_cache desc, created_at desc').page params[:page]

    respond_to do |format|
      format.html { render action: :index }
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    #increment view_count
    @post.view_count = @post.view_count+1
    @post.save!

    #put the current user into view scope
    @current_user = current_user

    #put an empty comment into scope.
    @comment = Comment.new(:post => @post)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :ok }
    end
  end

  #counterpoints

  #GET /posts/1/counterpoints/new
  #GET /posts/1/counterpoints/new.json
  def new_counterpoint
    @post = Post.new
    @parent_id = params[:id]

    respond_to do |format|
      format.html #template
      format.json { render json: @post }
    end
  end

  #POST /posts/1/counterpoints
  #POST /posts/1/counterpoints.json
  def create_counterpoint
    original = Post.find(params[:id])

    @post = original.counter_points.build(params[:post].merge({:user => current_user}))
    @post.counter_points << original

    respond_to do |format|
      #saving the original wraps everything up in one transaction.
      if original.save
        format.html { redirect_to @post, notice: 'Counter Point was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        @parent_id = original.id
        format.html { render action: "new_counterpoint" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def requires_author
    post = Post.find(params[:id])

    if not post.user_can_edit?(current_user)
      redirect_to post, alert: "You must be the article author to edit an article!"
    end
  end

  def requires_new_author
    post = Post.find(params[:id])

    if not post.user_can_post_counterpoint?(current_user)
      redirect_to post, alert: "You cannot create a counterpoint for your own post!"
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>

  <div class="field">
    <%= f.label :tags %>
    <%= f.text_field :tag_list %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post_synopsis.html.erb
<div class="post">
  <div class="post-title"><%= link_to post.title, post_path(post) %></div>
  <div class="post-info">by <strong><%= link_to post.user.username, member_path(post.user) %></strong> <%= post.user.rep %> posted: <%= distance_of_time_in_words_to_now post.created_at %> ago Comments: <%= post.comments.count %> Views: <%= post.view_count %> Up: <%= post.up_vote_count %> Down: <%= post.down_vote_count %> Counter Points: <%= post.counter_points.count %></div>
  <div class="tag-list">Topics: <%= post.tags.map(&:name).join(', ') %></div>
  <%#= link_to 'view', post_path(post) %>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

<script type="text/javascript">
  $(document).ready(function(){
    $('#post_body').ckeditor(function(){/* callback code */}, { toolbar: 'Basic'});
  });
</script>

app/views/posts/index.html.erb
<div class='row'>
  <div class="span9">
    <h1>Latest Discussions</h1>
    <ul class="nav nav-tabs">
      <li class="pull-right <%= "active" if controller.action_name == 'popular_posts' %>"><%= link_to 'Popular', popular_posts_path %></li>
      <li class="pull-right <%= "active" if controller.action_name == 'index' %>"><%= link_to 'Recent', posts_path %></li>
    </ul>
  </div>
</div>
<div style="clear: both;"></div>
<%= render :partial => 'post_synopsis', :collection => @posts, :as => :post %>
<%= paginate @posts %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

<script type="text/javascript">
  $(document).ready(function(){
    $('#post_body').ckeditor(function(){/* callback code */}, { toolbar: 'Basic', resize_enabled: false });
  });
</script>

app/views/posts/new_counterpoint.html.erb
<h1>New Counter Point</h1>

<%#TODO consolidate this form into a partial %>

<%= form_for(@post, :url => post_counterpoints_path(:id => @parent_id)) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script type="text/javascript">
  $(document).ready(function(){
    $('#post_body').ckeditor(function(){/* callback code */}, { toolbar: 'Basic'});
  });
</script>

app/views/posts/show.html.erb
<div id="post-view-title">
<h1><%= @post.title %></h1>
<%= link_to @post.user.username, member_path(@post.user) %> <%= @post.user.rep %>  posted: <%= distance_of_time_in_words_to_now @post.created_at %> ago Comments: <%= @post.comments.count %> Views: <%= @post.view_count %> Up: <%= @post.up_vote_count %> Down: <%= @post.down_vote_count %>
<br />
Topics: <%= @post.tags.map(&:name).join(', ') %>
</div>

<div class="leaderboard-wrapper">
  <h3>Ad Content</h3>
</div>
<div class="post-body">
  <div><%= link_to 'Edit', edit_post_path(@post) if @post.user_can_edit?(@current_user) %></div>
  <%= @post.body.html_safe %>
</div>

<% if @post.user_can_vote?(@current_user) %>
    <p>
      <%= link_to 'Vote Up', vote_post_up_path(@post) %>
      <%= link_to 'Vote Down', vote_post_down_path(@post) %>
    </p>
<% end %>

<div><%= link_to 'Create Counterpoint', new_post_counterpoint_path(@post) if @post.user_can_post_counterpoint?(@current_user) %></div>

<% if @post.counter_points.size > 0 %>
    <h3 class="rule-header">Counter Points</h3>
    <% @post.counter_points.each do |counterpoint| %>
        <div class="post">
            <div class="post-title"><%= link_to counterpoint.title, post_path(counterpoint) %></div>
            <div class="post-info">by <strong><%= counterpoint.user.username %></strong> <%= counterpoint.user.rep %> on <%= l counterpoint.created_at %> Comments: <%= counterpoint.comments.count %> Views: <%= counterpoint.view_count %> Up: <%= counterpoint.up_vote_count %> Down: <%= counterpoint.down_vote_count %> Counter Points: <%= counterpoint.counter_points.count %></div>

            <%#= link_to 'view', post_path(post) %>
        </div>
    <% end %>
<% end %>

<% if not @post.comments.empty? %>
    <h3 class="rule-header">Comments</h3>
    <%# TODO remove? = link_to 'New Comment', new_post_comment_path(@post) %>
    <% if @post.comments.count > 0 %>
        <% @post.comments.each do |comment| %>
            <div class="comment-display <%= "comment-last" if comment == @post.comments.last %>">
                <div><strong><%= link_to comment.user.username, member_path(comment.user) %></strong> <%= comment.user.rep %>: posted <%= distance_of_time_in_words_to_now comment.created_at %> Up: <%= comment.up_vote_count %> Down: <%= comment.down_vote_count %></div>
                <p><%= comment.body.html_safe %></p>
                <% if comment.user_can_vote?(@current_user) %>
                    <p>
                      <%= link_to 'Vote Up', vote_comment_up_path(comment) %>
                      <%= link_to 'Vote Down', vote_comment_down_path(comment) %>
                    </p>
                <% end %>
            </div>
        <% end %>

    <% end %>
<% end %>
<hr />
<div id="comment-form">
  <h3>Your Comment</h3>
  <%= render 'comments/form' %>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $('#comment_body').ckeditor(function(){/* callback code */}, { toolbar: 'Basic', resize_enabled: false });
  });
</script>