config/routes.rb
Popdisco::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get 'posts/popular' => 'posts#popular_posts', :as => :popular_posts

  resources :posts do
    resources :comments
  end

  get 'organizations/recent' => 'organizations#recent_organizations', :as => :recent_organizations
  get 'organizations/reputation' => 'organizations#top_organizations', :as => :top_organizations
  get 'organizations/:id/join' => 'organizations#join', :as => :join_organization

  resources :organizations, :except => :destroy

  get "omniauth_callbacks/facebook"

  devise_for :users, :controllers => { :omniauth_callbacks => 'omniauth_callbacks' }

  resources :user_profiles, except: [:index, :show, :destroy]

  get 'members' => 'members#index'
  get 'members/recent' => 'members#recent_members', :as => :recent_members
  get 'members/reputation' => 'members#members_by_reputation', :as => :top_members
  get 'members/:id' => 'members#show', :as => :member

  get 'posts/:id/counterpoints/new' => 'posts#new_counterpoint', :as => :new_post_counterpoint
  post 'posts/:id/counterpoints' => 'posts#create_counterpoint', :as => :post_counterpoints

  get 'topics/:tag/posts' => 'tags#posts_by_tag', :as => :posts_by_tag
  get 'topics' => 'tags#index'
  get 'topics/recent' => 'tags#recent_tags', :as => :recent_topics
  get 'topics/popular' => 'tags#popular_tags', :as => :popular_topics

  match 'vote/post/:post_id/up' => 'votes#vote_post_up', :as => :vote_post_up
  match 'vote/post/:post_id/down' => 'votes#vote_post_down', :as => :vote_post_down
  match 'vote/comment/:comment_id/up' => 'votes#vote_comment_up', :as => :vote_comment_up
  match 'vote/comment/:comment_id/down' => 'votes#vote_comment_down', :as => :vote_comment_down

  get "achievements" => 'achievements#index', :as => :achievements
  get "achievements/:id" => 'achievements#show', :as => :achievement

  get "achievements/show"

  root :to => 'posts#index'

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :affiliations
  has_many :members, :through => :affiliations, :class_name => 'User', :source => :user

  def user_can_edit?(user)
    if user.nil?
      false
    else
      affiliation = self.affiliations.find_by_user_id(user.id)

      (!affiliation.nil? and affiliation.admin?)
    end
  end

  def user_is_a_member?(user)
    if user.nil?
      false
    else
      self.affiliations.where(user_id: user.id).any?
    end
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_filter :authenticate_user!, :only =>  [:join, :new, :create, :edit, :update]
  before_filter :require_organization_admin, only: [:edit, :update]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.where('enabled = ?', true).order('name asc').all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @organizations }
    end
  end

  def recent_organizations
    @organizations = Organization.where('enabled = ?', true).order('created_at desc, name asc').all()

    respond_to do |format|
      format.html { render action: 'index' }
      format.json { render json: @organization }
    end
  end

  def top_organizations
    @organizations = Organization.where('enabled = ?', true).order('rep desc, name asc').all()

    respond_to do |format|
      format.html { render action: 'index' }
      format.json { render json: @organizations }
    end
  end

  def join
    @organization = Organization.find(params[:id])
    @affiliation = @organization.affiliations.build(user_id: current_user.id, owner: false, admin: false)

    respond_to do |format|
      if @affiliation.save
        format.html { redirect_to @organization, notice: "You have signed up to be a member of #{@organization.name}" }
        format.json { render json: @organization }
      else
        format.html { redirect_to @organization, alert: @affiliation.errors.full_messages[0] }
        format.json { render json: @affiliation.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @organization = Organization.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/new
  # GET /organizations/new.json
  def new
    @organization = Organization.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/1/edit
  def edit
    @organization = Organization.find(params[:id])
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(params[:organization].merge({enabled: true}))

    #default the creating user to be the owner/admin of the group.
    @organization.affiliations.build(user: current_user, rep: 10, owner: true, admin: true)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render json: @organization, status: :created, location: @organization }
      else
        format.html { render action: "new" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /organizations/1
  # PUT /organizations/1.json
  def update
    @organization = Organization.find(params[:id])

    respond_to do |format|
      if @organization.update_attributes(params[:organization])
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def require_organization_admin
    organization = Organization.find(params[:id])

    #affiliation = organization.affiliations.find_by_user_id(current_user.id)

    if not organization.user_can_edit?(current_user)
      redirect_to organization, alert: "You must be an organization admin to edit the organization."
    end
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script type="text/javascript">
  $(document).ready(function(){
    $('#organization_description').ckeditor(function(){/* callback code */}, { toolbar: 'Basic', resize_enabled: false });
  });
</script>

app/views/organizations/edit.html.erb
<h1>Editing organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<div class="row">
  <div class="span9">
    <h1>Organizations</h1>

    <ul class="nav nav-tabs">
      <li class="pull-right <%= "active" if controller.action_name == 'index' %>"><%= link_to 'All', organizations_path %></li>
      <li class="pull-right <%= "active" if controller.action_name == 'recent_organizations' %>"><%= link_to 'Recent', recent_organizations_path %></li>
      <li class="pull-right <%= "active" if controller.action_name == 'top_organizations' %>"><%= link_to 'Reputation', top_organizations_path %></li>
    </ul>
  </div>
</div>

<div class="row">
    <ul class="grid-list organizations-grid">
    <% @organizations.each do |organization| %>
        <li class="well">
            <%= link_to organization.name, organization_path(organization) %>
            <br /><%= organization.affiliations.count %> Members
            <br /><%= organization.rep %> Reputation
        </li>
    <% end %>
    </ul>
</div>

<%= link_to 'New Organization', new_organization_path, class: 'btn' %>

app/views/organizations/new.html.erb
<h1>New organization</h1>

<%= render 'form' %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<h1><%= @organization.name %></h1>
<div><span>Stats: </span> <%= @organization.affiliations.count %> members, <%= @organization.rep %> Reputation</div>
<hr />
<p><%= @organization.description.html_safe %></p>

<%= link_to 'Back', organizations_path %>
<% if user_signed_in? %>
    <%= link_to 'Edit', edit_organization_path(@organization) if @organization.user_can_edit?(current_user) %>
    <%= link_to 'Join', join_organization_path(@organization) if not @organization.user_is_a_member?(current_user) %>
<% end %>