config/routes.rb
Popdisco::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get 'posts/popular' => 'posts#popular_posts', :as => :popular_posts

  resources :posts do
    resources :comments
  end

  get 'organizations/recent' => 'organizations#recent_organizations', :as => :recent_organizations
  get 'organizations/reputation' => 'organizations#top_organizations', :as => :top_organizations
  get 'organizations/:id/join' => 'organizations#join', :as => :join_organization

  resources :organizations, :except => :destroy

  get "omniauth_callbacks/facebook"

  devise_for :users, :controllers => { :omniauth_callbacks => 'omniauth_callbacks' }

  resources :user_profiles, except: [:index, :show, :destroy]

  get 'members' => 'members#index'
  get 'members/recent' => 'members#recent_members', :as => :recent_members
  get 'members/reputation' => 'members#members_by_reputation', :as => :top_members
  get 'members/:id' => 'members#show', :as => :member

  get 'posts/:id/counterpoints/new' => 'posts#new_counterpoint', :as => :new_post_counterpoint
  post 'posts/:id/counterpoints' => 'posts#create_counterpoint', :as => :post_counterpoints

  get 'topics/:tag/posts' => 'tags#posts_by_tag', :as => :posts_by_tag
  get 'topics' => 'tags#index'
  get 'topics/recent' => 'tags#recent_tags', :as => :recent_topics
  get 'topics/popular' => 'tags#popular_tags', :as => :popular_topics

  match 'vote/post/:post_id/up' => 'votes#vote_post_up', :as => :vote_post_up
  match 'vote/post/:post_id/down' => 'votes#vote_post_down', :as => :vote_post_down
  match 'vote/comment/:comment_id/up' => 'votes#vote_comment_up', :as => :vote_comment_up
  match 'vote/comment/:comment_id/down' => 'votes#vote_comment_down', :as => :vote_comment_down

  get "achievements" => 'achievements#index', :as => :achievements
  get "achievements/:id" => 'achievements#show', :as => :achievement

  get "achievements/show"

  root :to => 'posts#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Popdisco</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body id="<%= "#{controller.controller_name}_#{controller.action_name}" %>">
    <!--<p class="notice"><%= notice %></p>-->
    <!--<p class="alert"><%= alert %></p>-->
    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
          <%=  link_to 'Popdisco', root_path, class: 'brand' %>
            <div class="container">
              <ul class="nav">
              <% if user_signed_in? %>
                <li><%= link_to current_user.username, member_path(current_user) %> <%= current_user.rep %></li>
                <li><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %></li>
              <% else %>
                <li><%= link_to 'Sign In',  new_user_session_path %></li>
              <% end %>
              <li><%= link_to 'Articles', root_path %></li>
              <li><%= link_to 'Topics', popular_topics_path %></li>
              <% if user_signed_in? %><li><%= link_to 'Members', top_members_path %></li><% end %>
              <li><%= link_to 'Organizations', top_organizations_path %></li>
              <li><%= link_to 'Achievements', achievements_path %></li>
            </ul>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
              <div class="span2">
                  <div id="logo-wrapper">
                    <%= link_to 'Logo', root_path, id: 'logo-home-link' %>
                  </div>
              </div>
              <div class="span2 offset8"><%= link_to 'Create Post', new_post_path, id: 'header-post-create-btn', class: 'btn btn-primary btn-large' %></div>
        </div>
        <div class="row">
          <div class="span9"><%= yield %></div>
          <div class="span3">
            <div id='sidebar-ad-wrapper'>
              <h3>sidebar ad</h3>
            </div>
            <div id='recent-tags-wrapper'>
              <h3>Recent Topics</h3>
              <ul>
                <% recent_tags.each do |tag| %>
                    <li><%= link_to "#{tag.name} (#{tag.count})", posts_by_tag_path(:tag => tag.name) %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
    </div>

    <div style="clear:both;"></div>
    <div id="footer">
      <p>Some Footer Stuff</p>
    </div>
</body>
</html>