config/routes.rb
Popdisco::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get 'posts/popular' => 'posts#popular_posts', :as => :popular_posts

  resources :posts do
    resources :comments
  end

  get 'organizations/recent' => 'organizations#recent_organizations', :as => :recent_organizations
  get 'organizations/reputation' => 'organizations#top_organizations', :as => :top_organizations
  get 'organizations/:id/join' => 'organizations#join', :as => :join_organization

  resources :organizations, :except => :destroy

  get "omniauth_callbacks/facebook"

  devise_for :users, :controllers => { :omniauth_callbacks => 'omniauth_callbacks' }

  resources :user_profiles, except: [:index, :show, :destroy]

  get 'members' => 'members#index'
  get 'members/recent' => 'members#recent_members', :as => :recent_members
  get 'members/reputation' => 'members#members_by_reputation', :as => :top_members
  get 'members/:id' => 'members#show', :as => :member

  get 'posts/:id/counterpoints/new' => 'posts#new_counterpoint', :as => :new_post_counterpoint
  post 'posts/:id/counterpoints' => 'posts#create_counterpoint', :as => :post_counterpoints

  get 'topics/:tag/posts' => 'tags#posts_by_tag', :as => :posts_by_tag
  get 'topics' => 'tags#index'
  get 'topics/recent' => 'tags#recent_tags', :as => :recent_topics
  get 'topics/popular' => 'tags#popular_tags', :as => :popular_topics

  match 'vote/post/:post_id/up' => 'votes#vote_post_up', :as => :vote_post_up
  match 'vote/post/:post_id/down' => 'votes#vote_post_down', :as => :vote_post_down
  match 'vote/comment/:comment_id/up' => 'votes#vote_comment_up', :as => :vote_comment_up
  match 'vote/comment/:comment_id/down' => 'votes#vote_comment_down', :as => :vote_comment_down

  get "achievements" => 'achievements#index', :as => :achievements
  get "achievements/:id" => 'achievements#show', :as => :achievement

  get "achievements/show"

  root :to => 'posts#index'

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
    @members = User.all

    respond_to do |format|
      format.html #render template
      format.json { render json: @members }
    end
  end

  def show
    @member = User.find(params[:id])

    respond_to do |format|
      format.html #render template
      format.json { render json: @member }
    end
  end

  def recent_members
    @members = User.order('created_at desc, username asc').all()

    respond_to do |format|
      format.html { render action: 'index' }
      format.json { render json: @members }
    end
  end

  def members_by_reputation
    @members = User.order('rep desc, username asc').all()

    respond_to do |format|
      format.html { render action: 'index' }
      format.json { render json: @members }
    end
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/index.html.erb
<div class="list-header">
    <h1>Members</h1>
    <ul>
        <li><%= link_to 'Reputation', top_members_path %></li>
        <li><%= link_to 'Recent', recent_members_path %></li>
        <li><%= link_to 'Name', members_path %></li>
    </ul>
</div>
<div style="clear: both"></div>
<hr />
<ul class="list-grid members-grid">
<% @members.each do |member| %>
    <li>
        <%= link_to member.username, member_path(member) %>
        <div><%= member.rep %> Rep</div>
        <div><%= "#{member.achievements.size} #{(member.achievements.size > 1 or member.achievements.size == 0) ? 'Achievements' : 'Achievement'}" %></div>
        <div><%= "#{member.posts.size} #{(member.posts.size > 1 or member.posts.size == 0) ? 'Posts' : 'Post' }" %></div>
        <%= image_tag member.avatar.url(:icon), float: 'right' %>
    </li>
<% end %>
</ul>

app/views/members/show.html.erb
<h1>Member Profile For <%= @member.username %></h1>
<hr />
<% if user_signed_in? and @member.eql? current_user %>
    <%= link_to 'Edit Profile', edit_user_profile_path(@member.user_profile) if not @member.user_profile.nil? %>
    <%= link_to 'Create Profile', new_user_profile_path if @member.user_profile.nil? %>
<% end %>

<% if @member.avatar %>
    <%= image_tag @member.avatar.url %>
<% end %>

<% if not @member.user_profile.nil? %>
    <div>
      Name: <%= @member.user_profile.name %>
    </div>

    <div>
      Website: <%= @member.user_profile.website %>
    </div>

    <div>
      Age: <%= distance_of_time_in_words_to_now( @member.user_profile.birthday ) %>
    </div>

    <div>
      Location: <%= @member.user_profile.location %>
    </div>

    <div>
      Bio: <%= @member.user_profile.bio.html_safe %>
    </div>
<% end %>


<% if not @member.organizations.empty? %>
<h2>My Organizations</h2>
<hr />
<ul>
  <% @member.organizations.each do |org| %>
    <li><%= link_to org.name, organization_path(org) %></li>
  <% end %>
</ul>
<% end %>

<h2>My Achievements</h2>
<hr />
<ul>
  <% @member.achievements.each do |achievement| %>
    <li><%= link_to achievement.name, achievement_path(achievement) %></li>
  <% end %>
</ul>

<h2>My Articles</h2>
<hr />
<%= render :partial => 'posts/post_synopsis', :collection => @member.posts, :as => :post %>